version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend_network
    environment:
      - BACKEND_URL=http://backend:5000

  backend:
    build: ./backend
    expose:
      - "5000"
    networks:
      - backend_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  load_balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - frontend_network
      - backend_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

networks:
  frontend_network:
  backend_network: