version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mongo:4.1
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data: