version: '3'
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
  backend:
    build: ../backend
    ports:
      - "8080:8080"
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

